-- Vitia — Supabase database setup
-- Run this in the Supabase SQL Editor after creating your project.
-- https://supabase.com/dashboard > SQL Editor > New query

-- ── users_profile ────────────────────────────────────────────────────────────
create table if not exists users_profile (
  user_id           text primary key,           -- auth.uid()::text
  age               integer not null,
  height_cm         real not null,
  weight_kg         real not null,
  sex               text not null check (sex in ('male', 'female')),
  activity_level    text not null check (activity_level in (
                      'sedentary', 'lightly_active', 'moderately_active',
                      'very_active', 'extra_active')),
  goal              text not null check (goal in ('lose_weight', 'maintain', 'gain_muscle')),
  calorie_goal      real not null,
  protein_goal_g    real not null,
  carbs_goal_g      real not null,
  fat_goal_g        real not null,
  use_manual_goals  boolean not null default false,
  created_at        text not null default (now()::text),
  updated_at        text not null default (now()::text)
);

alter table users_profile enable row level security;

-- Users can only read and write their own profile
create policy "users_profile: own row only"
  on users_profile
  for all
  using (auth.uid()::text = user_id)
  with check (auth.uid()::text = user_id);


-- ── meal_entries ─────────────────────────────────────────────────────────────
create table if not exists meal_entries (
  id           text primary key,               -- UUID (generated by client)
  user_id      text not null,
  date         text not null,                  -- YYYY-MM-DD
  meal_type    text not null check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  food_id      text not null,
  food_name    text not null,
  quantity_g   real not null,
  calories     real not null,
  protein_g    real not null,
  carbs_g      real not null,
  fat_g        real not null,
  logged_at    text not null default (now()::text),
  updated_at   text
);

alter table meal_entries enable row level security;

-- Users can only read and write their own entries
create policy "meal_entries: own rows only"
  on meal_entries
  for all
  using (auth.uid()::text = user_id)
  with check (auth.uid()::text = user_id);

-- Index for common date-based queries
create index if not exists meal_entries_user_date_idx on meal_entries (user_id, date);


-- ── foods (global — no per-user isolation needed) ────────────────────────────
-- Note: foods is a shared OFF cache + custom catalog.
-- If you want users to have private custom foods in future, add a user_id column.
create table if not exists foods (
  id                  text primary key,
  name                text not null,
  brand               text,
  calories_per_100g   real not null,
  protein_per_100g    real not null default 0,
  carbs_per_100g      real not null default 0,
  fat_per_100g        real not null default 0,
  serving_size_g      real,
  source              text not null check (source in ('openfoodfacts', 'custom')),
  off_product_code    text,
  name_normalized     text not null default '',
  created_at          text not null default (now()::text)
);

-- No RLS on foods (global table); add anon read if you want unauthenticated search.


-- ── After setup ──────────────────────────────────────────────────────────────
-- 1. Copy your project URL and anon key from:
--    Supabase dashboard > Project Settings > API
-- 2. Add to Vercel environment variables:
--    VITE_SUPABASE_URL=https://<project-ref>.supabase.co
--    VITE_SUPABASE_ANON_KEY=<your-anon-key>
--    VITE_SYNC_ENABLED=true
-- 3. Update connect-src in vercel.json to include:
--    https://<project-ref>.supabase.co
-- 4. Enable Google OAuth in Supabase dashboard:
--    Authentication > Providers > Google
--    (Follow Supabase docs to set up the Google Cloud OAuth credentials)
