/**
 * Converts processed BEDCA food records into idempotent SQL INSERT statements
 * for the generic_foods table.
 *
 * name_normalized is computed using the same normalizeForSearch() helper as
 * the rest of the app (lib/search.ts) to guarantee consistency with ilike
 * searches.
 */

import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

// Node-compatible normalizeForSearch: same algorithm as lib/search.ts.
// Kept in sync by test 5.7 (any divergence from lib/search.ts will be caught).
function normalizeForSearch(s: string): string {
  return s.normalize("NFKD").replace(/\p{M}/gu, "").toLowerCase().trim();
}

// ── Types ────────────────────────────────────────────────────────────────────

export interface SeedRecord {
  id: string; // UUID (pre-generated by run.ts)
  name: string;
  calories_per_100g: number;
  protein_per_100g: number;
  carbs_per_100g: number;
  fat_per_100g: number;
  category: string | null;
  data_basis: "crudo" | "cocido" | null;
}

// ── SQL helpers ───────────────────────────────────────────────────────────────

function sqlStr(value: string | null): string {
  if (value === null) return "NULL";
  // Escape single quotes by doubling them (SQL standard).
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNum(value: number): string {
  // Guard against NaN/Infinity — default to 0.
  if (!Number.isFinite(value)) return "0";
  return String(value);
}

/**
 * Derives a deterministic, content-derived UUID from a food's canonical
 * identity (baseName + category), so identical canonical foods produce the
 * identical id across separate pipeline runs and ON CONFLICT (id) DO NOTHING
 * correctly dedups on rerun.
 *
 * The id is scoped to canonical identity only (not raw nutrient values) — see
 * design Correction 2: post-grouping there is exactly one row per
 * (baseName, category), so two records sharing that identity MUST share the
 * same id regardless of differing raw nutrient values.
 */
export function stableFoodId(baseName: string, category: string | null): string {
  const hash = createHash("sha256")
    .update(`${baseName}|${category ?? ""}`)
    .digest("hex");
  const hex = hash.slice(0, 32);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

function buildInsert(record: SeedRecord): string {
  const nameNormalized = normalizeForSearch(record.name);

  return `INSERT INTO generic_foods (id, name, name_normalized, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, category, data_basis, source) VALUES (${sqlStr(record.id)}, ${sqlStr(record.name)}, ${sqlStr(nameNormalized)}, ${sqlNum(record.calories_per_100g)}, ${sqlNum(record.protein_per_100g)}, ${sqlNum(record.carbs_per_100g)}, ${sqlNum(record.fat_per_100g)}, ${sqlStr(record.category)}, ${sqlStr(record.data_basis)}, 'bedca') ON CONFLICT (id) DO NOTHING;`;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Generates the seed SQL file from processed records.
 *
 * @param records  The seed records to write.
 * @param outputFile  Absolute path to the output SQL file. The caller (run.ts)
 *                    resolves this path using import.meta.url so this module
 *                    stays free of import.meta — safe under ts-jest (CJS).
 * @returns  Number of records written.
 */
export function generateSeedSql(records: SeedRecord[], outputFile: string): number {
  mkdirSync(dirname(outputFile), { recursive: true });

  const header = [
    "-- generic_foods seed data from BEDCA v1.0",
    `-- Generated: ${new Date().toISOString()}`,
    `-- Records: ${records.length}`,
    "-- Idempotent: ON CONFLICT (id) DO NOTHING",
    "-- Self-reconciling: deletes existing source='bedca' rows before reinserting",
    "-- the deduplicated set, atomically, in the same transaction.",
    "-- Apply manually via Supabase SQL Editor.",
    "",
    "BEGIN;",
    "",
    "DELETE FROM generic_foods WHERE source = 'bedca';",
    "",
  ].join("\n");

  const inserts = records.map(buildInsert).join("\n");

  const footer = [
    "",
    "COMMIT;",
    "",
    "-- Verify: SELECT count(*), source FROM generic_foods GROUP BY source;",
  ].join("\n");

  writeFileSync(outputFile, header + inserts + footer, "utf8");

  return records.length;
}
